---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mysql-server
  namespace: cloudy
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3306
  selector:
    app: nextcloud-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  namespace: cloudy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        name: mysql
        env:
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud-mysql-password
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        # This volume is backed by a Ceph block device
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-rbd-pvc
          readOnly: false