---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-server
  namespace: cloudy
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 31880
  selector:
    app: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mysql-server
  namespace: cloudy
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3306
  selector:
    app: nextcloud-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  namespace: cloudy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        # This volume is backed by a Ceph block device
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-rbd-pvc
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: cloudy
spec:
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - image: nextcloud:21-apache
        env:
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud-admin-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: 10.149.*
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_HOST
          value: nextcloud-mysql-server.cloudy:3306
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud-mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: mysql-root-password
        name: nextcloud
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: nextcloud-persistent-storage
          mountPath: /var/www/html/
      volumes:
        # This volume is backed by a Ceph block device
      - name: nextcloud-persistent-storage
        persistentVolumeClaim:
          claimName: nextcloud-rbd-pvc
          readOnly: false