---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-rbd-pvc
  namespace: cloudy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-rbd-pvc
  namespace: cloudy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block
