apiVersion: v1
data:
  nextcloud-setup.sql: |-
    CREATE USER 'nextcloud'@'';
    SET PASSWORD FOR 'nextcloud'@'' = PASSWORD('nextcloudpass');
    GRANT ALL ON nextcloud.* TO 'nextcloud'@'';
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: cloudy
