apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: cloudy
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cloudy
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: CHANGEme
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        # This volume is backed by a Ceph block device
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-rbd-pvc
          readOnly: false
      - name: mysql-initdb
        configMap:
          name: mysql-configmap