---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-rbd-pvc
  namespace: cloudy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
