apiVersion: v1
kind: Service
metadata:
  name: mosquitto-server
  namespace: cloudy
spec:
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
  - name: http
    protocol: TCP
    port: 9001
  selector:
    app: mosquitto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: cloudy
spec:
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:2.0.10
        name: mosquitto
        ports:
        - containerPort: 1883
          protocol: TCP
          name: mqtt
        - containerPort: 9001
          protocol: TCP
          name: http
        volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config